cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hw/", include("hw.urls")),
    path("quotes/", include("quotes.urls")),
    path("formdata/", include("formdata.urls")),
    path("blog/", include("blog.urls")),
    path("mini_fb/", include("mini_fb.urls")),
    path("voter_analytics/", include("voter_analytics.urls")),
    path("project/", include("project.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static    ## add for static files
from . import views



urlpatterns = [ 
    # path(r'', views.home, name="home"),
    path(r'', views.home_page, name="home_page"),
    path(r'about', views.about, name="about_page"),

] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mini_fb/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static    ## add for static files
from . import views
from django.contrib.auth import views as auth_views 

from .views import *

urlpatterns = [
    path('', ShowAllProfilesView.as_view(), name="ShowAllProfilesView"),
    path('profile/<int:pk>', ShowProfilePageView.as_view(), name='show_profile'),# new
    path('create_profile', CreateProfileView.as_view(), name="create_profile"), # new
    path('status/create_status', CreateStatusMessageView.as_view(), name='create_status'),
    path('profile/update', UpdateProfileView.as_view(), name='update_profile'),
    path('status/<int:pk>/delete', DeleteStatusMessageView.as_view(), name ='delete'),
    path("status/<int:pk>/update", UpdateStatusMessageView.as_view(), name='update_status'),
    path('profile/add_friend/<int:other_pk>', AddFriendView.as_view(), name='add_friend'),
    path('profile/friend_suggestions', ShowFriendSuggestionsView.as_view(), name='friend_suggestions'),
    path('profile/news_feed', ShowNewsFeedView.as_view(), name='news_feed'),
    path('login/', auth_views.LoginView.as_view(template_name='mini_fb/login.html', ), name='login'), ## NEW
    path('logout/', auth_views.LogoutView.as_view(template_name='mini_fb/logged_out.html'), name="logout"),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mini_fb/models.py
"""
File: models.py
Author: Sam Bridgman
Email: bridgman@bu.edu
Description: Defines the Profile model, which stores user profile details, including 
name, city, email, and profile image URL. This model is used to represent users 
in the Mini FB application. Also displays the Status Message Model for creating messages
"""

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    """Encapsulate the idea of a Profile, representing a user's basic information."""

    # data attributes of a Profile:
    first_name = models.TextField(blank=False)
    last_name = models.TextField(blank=False)
    city = models.TextField(blank=False)
    email = models.TextField(blank=False)
    profile_image_url = models.URLField(blank=True) ## new
    user = models.ForeignKey(User, on_delete=models.CASCADE) ## NEW


    def get_status_messages(self):
        messages = StatusMessage.objects.filter(profile=self)
        return messages
    
    def get_absolute_url(self):
        return reverse('show_profile',kwargs={'pk':self.pk})
    
    def get_friends(self):
        """Return a list of Profile instances representing this user's friends."""
        friends = Friend.objects.filter(models.Q(profile1=self) | models.Q(profile2=self))
        return [friend.profile2 if friend.profile1 == self else friend.profile1 for friend in friends]
    
    
    
    def add_friend(self, other):
        """Add a friend relationship between self and another Profile.
        """
        if self == other:
            return  # Prevents selffriending

        # Check if a friendship already exists
        existing_friendship = Friend.objects.filter(
            models.Q(profile1=self, profile2=other) | models.Q(profile1=other, profile2=self)
        ).exists()

        if not existing_friendship:
            Friend.objects.create(profile1=self, profile2=other)
    
    def get_friend_suggestions(self):
        """
        Returns a list of suggested friends (Profiles) for this Profile.
        Suggestions are based on "friends of friends" who are not already friends with self.
        """
        current_friends = self.get_friends()

        # Get friends of friends
        friends_of_friends = Profile.objects.filter(
            models.Q(profile1__profile2__in=current_friends) | models.Q(profile2__profile1__in=current_friends)
        ).exclude(pk=self.pk).exclude(pk__in=[friend.pk for friend in current_friends]).distinct()

        return friends_of_friends
    
    def get_news_feed(self):

        friends = self.get_friends()

        news_feed = StatusMessage.objects.filter(
            models.Q(profile=self) | models.Q(profile__in=friends)
        ).order_by('-timestamp')  

        return news_feed




    def __str__(self):
        '''Return a string representation of this Profile object.'''
        return f'{self.first_name}, {self.last_name}'
    
class StatusMessage(models.Model):
    # Model to store status messages associated with user profiles.
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    message = models.TextField(blank=False)

    def __str__(self):
        return f'{self.message}'
    
    def get_images(self):
        """Return all images associated with this StatusMessage."""
        return Image.objects.filter(statusimage__status_message=self)

    
class Image(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image_file = models.ImageField(blank=True)
    timestamp = models.DateTimeField(auto_now=True)
    caption = models.TextField(blank=True, null=True)  # Optional description

    def __str__(self):
        return f'Image uploaded by {self.profile.first_name}'

class StatusImage(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    status_message = models.ForeignKey(StatusMessage, on_delete=models.CASCADE)

    def __str__(self):
        return f'Image associated with status: {self.status_message}'
    
class Friend(models.Model):
    profile1 = models.ForeignKey(Profile, related_name="profile1", on_delete=models.CASCADE)
    profile2 = models.ForeignKey(Profile, related_name="profile2", on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Friends {self.profile1.first_name} & {self.profile2.first_name}'

mini_fb/forms.py
from django import forms
from .models import Profile, StatusMessage

class CreateProfileForm(forms.ModelForm):
# Form for creating a new user profile.

    class Meta:
        model = Profile
        fields = ['first_name','last_name','city','email', 'profile_image_url']

class CreateStatusMessageForm(forms.ModelForm):
# Form for creating a new status message.

    class Meta:
        
        model = StatusMessage
        fields = ['message']

class UpdateProfileForm(forms.ModelForm):
# Form for updating profile attributes

    class Meta:
        model = Profile
        fields = ['city', 'email', 'profile_image_url']

mini_fb/views.py
"""
File: views.py
Author: Sam Bridgman
Email: bridgman@bu.edu
Description: Defines views for displaying user profiles in the Mini FB application.
Includes a ListView to display all profiles and a DetailView to show individual 
profile details.
"""
from django.urls import reverse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View, TemplateView
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin ## NEW
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


from .forms import *
from django.shortcuts import redirect


class ShowAllProfilesView(ListView):
    """
    View to display all profiles in the system.
    Uses a ListView to retrieve and display all Profile objects.
    """
    model = Profile
    template_name = 'mini_fb/show_all_profiles.html'
    context_object_name = 'profiles' 

class ShowProfilePageView(DetailView):
    """
    View to display the details of a single profile.
    Uses a DetailView to retrieve and display a specific Profile object.
    """
    model = Profile
    template_name = 'mini_fb/show_profile.html'  # Reusing the same template
    context_object_name = 'profile'

class CreateProfileView(CreateView):
    model = Profile
    template_name = "mini_fb/create_profile_form.html"
    form_class = CreateProfileForm
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'user_form' not in context:
            context['user_form'] = UserCreationForm()
        return context

    def post(self, request, *args, **kwargs):
        # Create both forms with POST data
        self.object = None
        profile_form = self.get_form()
        user_form = UserCreationForm(request.POST)

        if profile_form.is_valid() and user_form.is_valid():
            # Save user and log them in
            user = user_form.save()
            login(request, user)

            # Save profile, attach user to it
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            return self.form_valid(profile_form)
        else:
            return self.form_invalid(profile_form)

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('show_profile', kwargs={'pk': self.object.pk})


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = UpdateProfileForm
    template_name = 'mini_fb/update_profile_form.html'

    def get_login_url(self) -> str:
        '''return the URL required for login'''
        return reverse('login') 
    
    def get_object(self):
        return Profile.objects.get(user=self.request.user)


class CreateStatusMessageView(LoginRequiredMixin, CreateView):
    template_name = 'mini_fb/create_status_form.html'
    form_class = CreateStatusMessageForm

    def get_login_url(self):
        return reverse('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        context['profile'] = profile
        return context

    def form_valid(self, form):
        status_message = form.save(commit=False)
        profile = Profile.objects.get(user=self.request.user)
        status_message.profile = profile
        status_message.save()

        files = self.request.FILES.getlist('files')
        for file in files:
            image = Image(profile=profile, image_file=file)
            image.save()
            status_image = StatusImage(image=image, status_message=status_message)
            status_image.save()

        return super().form_valid(form)

    def get_success_url(self):
        profile = Profile.objects.get(user=self.request.user)
        return reverse('show_profile', kwargs={'pk': profile.pk})


class DeleteStatusMessageView(LoginRequiredMixin,DeleteView):
    model = StatusMessage
    template_name = 'mini_fb/delete_status_form.html'
    context_object_name = "StatusMessage"

    def get_login_url(self) -> str:
        '''return the URL required for login'''
        return reverse('login') 

    def get_success_url(self):
        """
        Redirects the user to the correct profile page after successfully deleting a status message.
        """
        pk = self.object.profile.pk 
        return reverse('show_profile', kwargs={'pk':pk})

class UpdateStatusMessageView(LoginRequiredMixin, UpdateView):
    model = StatusMessage
    template_name = 'mini_fb/update_status_form.html'
    context_object_name = "StatusMessage"
    fields = ['message']

    def get_login_url(self) -> str:
        '''return the URL required for login'''
        return reverse('login') 

    def get_success_url(self):
        """
        Redirects the user to the correct profile page after successfully updating a status message.
        """
        pk = self.object.profile.pk 
        return reverse('show_profile', kwargs={'pk':pk})
    
class AddFriendView(LoginRequiredMixin, View):
    def get_login_url(self):
        return reverse('login')

    def dispatch(self, request, *args, **kwargs):
        profile = Profile.objects.get(user=request.user)
        other_profile_pk = self.kwargs.get('other_pk')
        other_profile = Profile.objects.get(pk=other_profile_pk)

        profile.add_friend(other_profile)
        return redirect('show_profile', pk=profile.pk)

    
class ShowFriendSuggestionsView(LoginRequiredMixin, TemplateView):
    template_name = 'mini_fb/friend_suggestions.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        context['profile'] = profile
        context['friend_suggestions'] = profile.get_friend_suggestions()
        return context



class ShowNewsFeedView(LoginRequiredMixin, TemplateView):
    template_name = 'mini_fb/news_feed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        context['profile'] = profile
        context['news_feed'] = profile.get_news_feed()
        return context


class LogoutConfirmationView(TemplateView):
    template_name = 'mini_fb/logged_out.html'

mini_fb/templates/mini_fb/base.html
<!-- 
    File: mini_fb/templates/mini_fb/base.html
    Author: Sam Bridgman
    Email: bridgman@bu.edu
    Description: Base html
-->

{% load static %}
<html>
    <head>
        <title>Mini FB</title>
        <link rel="stylesheet" href="{% static 'mini_fb.css' %}">
    </head>
    <body>
        <header>
            <h1>Mini FB</h1>
            <nav>
                <ul>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'ShowAllProfilesView' %}">Show All Profiles</a></li>
                    <li><a href="{% url 'create_profile' %}">Create Profile</a></li>
                    <li><form id="logout-form" method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                      </form></li>

                    <!-- URLs for users who are not logged in -->
                    {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'ShowAllProfilesView' %}">Show All Profiles</a></li>
                    <li><a href="{% url 'create_profile' %}">Create Profile</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% if request.user.is_authenticated %}
        Logged in as: {{request.user}}
        {% else %}
        Not logged in.
        {% endif %}
    
    {% block content %}
    {% endblock %}    
  
    </body>
</html>

mini_fb/templates/mini_fb/create_profile_form.html
<!-- 
    File: mini_fb/templates/mini_fb/create_profile_form.html
    Author: Sam Bridgman
    Email: bridgman@bu.edu
    Description: Displays the HTML form for creating a profile
-->

{% extends 'mini_fb/base.html' %}
{% block content %}
  <h2>Create Your Profile</h2>
  <form method="post">
    {% csrf_token %}

    <h3>Account Info</h3>
    {{ user_form.as_p }}

    <h3>Profile Info</h3>
    {{ form.as_p }}

    <button type="submit">Create Account & Profile</button>
  </form>
{% endblock %}

mini_fb/templates/mini_fb/create_status_form.html
<!-- 
    File: mini_fb/templates/mini_fb/create_status_form.html
    Author: Sam Bridgman
    Email: bridgman@bu.edu
    Description: Displays the form for creating statuses for each profile
-->

{% extends 'mini_fb/base.html' %}

{% block content %}
<h1>Create Status Message</h1>

<form  method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{form.as_table}}
    </table>

    <input type="file" name = "files" multiple />

    <input type="submit" name="submit" value="Submit">
</form>
{% endblock %}

mini_fb/templates/mini_fb/delete_status_form.html
<!-- 
    File: mini_fb/templates/mini_fb/delete_status_form.html
    Author: Sam Bridgman
    Email: bridgman@bu.edu
    Description: Displays delete message
-->

{% extends "mini_fb/base.html" %}

{% block content %}
<div class="container">
    <h2>Confirm Delete</h2>
    <p>Are you sure you want to delete this status message?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

    <form method="get" action="{% url 'show_profile' pk=object.profile.pk %}">
        <button type="submit" class="btn btn-secondary">Cancel</button>
    </form>
</div>
{% endblock %}

mini_fb/templates/mini_fb/friend_suggestions.html
<!-- 
    File: mini_fb/templates/mini_fb/friend_suggestions.html
    Author: Sam Bridgman
    Description: Displays friend suggestions for a Profile, with links to add friends.
-->
{% extends 'mini_fb/base.html' %}

{% block content %}
<main style="max-width: 600px; margin: 20px auto; text-align: center; font-family: Arial, sans-serif;">

    <h1 style="font-size: 24px; font-weight: bold; margin-bottom: 15px;">Friend Suggestions for {{ profile.first_name }}</h1>

    <a href="{% url 'show_profile' profile.pk %}" 
       style="display: inline-block; margin: 15px 0; color: #007bff; text-decoration: none; font-size: 16px;">
       ← Back to Profile
    </a>

    {% if friend_suggestions %}
    <ul style="list-style: none; padding: 0; margin-top: 15px;">
        {% for suggestion in friend_suggestions %}
        <li style="display: flex; align-items: center; justify-content: space-between; padding: 10px; background: #f8f9fa; border-radius: 8px; margin-bottom: 8px; box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);">
            
            <a href="{% url 'show_profile' suggestion.pk %}" style="display: flex; align-items: center; text-decoration: none; color: black; flex-grow: 1;">
                {% if suggestion.profile_image_url %}
                <img src="{{ suggestion.profile_image_url }}" alt="{{ suggestion.first_name }}" 
                     style="width: 50px; height: 50px; border-radius: 50%; object-fit: cover; margin-right: 10px;">
                {% else %}
                <div style="width: 50px; height: 50px; background: #ddd; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; margin-right: 10px;">
                </div>
                {% endif %}
                <span style="font-size: 16px; font-weight: bold;">{{ suggestion.first_name }} {{ suggestion.last_name }}</span>
            </a>
            
            <a href="{% url 'add_friend' pk=profile.pk other_pk=suggestion.pk %}" 
               style="background: #007bff; color: white; padding: 5px 10px; border-radius: 5px; text-decoration: none; font-size: 14px;">
                Add Friend
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p style="color: #6c757d; font-style: italic; margin-top: 15px;">No friend suggestions available.</p>
    {% endif %}
</main>
{% endblock %}

mini_fb/templates/mini_fb/logged_out.html
<!-- templates/blog/templates/login.html -->
{% extends 'mini_fb/base.html' %}

{% block content %}
  <h2>You’ve been logged out.</h2>
  <p>Thanks for stopping by. Want to <a href="{% url 'login' %}">log in again?</a></p>
{% endblock %}

mini_fb/templates/mini_fb/login.html
<!-- templates/blog/templates/login.html -->
{% extends 'mini_fb/base.html' %}

{% block content %}
<!-- This basic authentication form works.
- need to set "next" to redirect to correct page.
-->

<h1>Login</h1>
<form method="post" action="{% url 'login' %}" >
    {% csrf_token %}
    {{form}}
    <!-- This basic login form works, but after login in
     assumed the existance of a page at /registration/profile, which
     does not exist.  -->
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% else %}
    <input type="hidden" name="next" value="{% url 'ShowAllProfilesView' %}">
    <button type="submit">Submit</button>
    {% endif %}
</form>


<hr>
{% endblock %}

mini_fb/templates/mini_fb/news_feed.html
<!-- 
    File: mini_fb/templates/mini_fb/news_feed.html
    Author: Sam Bridgman
    Description: Displays the news feed for a Profile, showing posts from the user and their friends.
-->
{% extends 'mini_fb/base.html' %}

{% block content %}
<main style="max-width: 600px; margin: 20px auto; text-align: center; font-family: Arial, sans-serif;">

    <h1 style="font-size: 24px; font-weight: bold; margin-bottom: 15px;">News Feed</h1>

    <a href="{% url 'show_profile' profile.pk %}" 
       style="display: inline-block; margin: 15px 0; color: #007bff; text-decoration: none; font-size: 16px;">
       ← Back to Profile
    </a>

    {% if news_feed %}
    <ul style="list-style: none; padding: 0; margin-top: 15px;">
        {% for status in news_feed %}
        <li style="display: flex; align-items: center; padding: 10px; background: #f8f9fa; border-radius: 8px; margin-bottom: 8px; box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);">
            
            {% if status.profile.profile_image_url %}
            <img src="{{ status.profile.profile_image_url }}" alt="{{ status.profile.first_name }}" 
                 style="width: 50px; height: 50px; border-radius: 50%; object-fit: cover; margin-right: 10px;">
            {% else %}
            <div style="width: 50px; height: 50px; background: #ddd; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; margin-right: 10px;">
                👤
            </div>
            {% endif %}

            <div style="flex-grow: 1; text-align: left;">
                <a href="{% url 'show_profile' status.profile.pk %}" 
                   style="font-weight: bold; text-decoration: none; color: black;">
                   {{ status.profile.first_name }} {{ status.profile.last_name }}
                </a>
                <p style="font-size: 14px; color: #333; margin: 5px 0;">{{ status.message }}</p>
                <span style="font-size: 12px; color: #6c757d;">{{ status.timestamp }}</span>
            </div>

        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p style="color: #6c757d; font-style: italic; margin-top: 15px;">No posts to show.</p>
    {% endif %}
</main>
{% endblock %}

mini_fb/templates/mini_fb/show_profile.html
<!-- 
    File: mini_fb/templates/mini_fb/show_profile.html
    Author: Sam Bridgman
    Email: bridgman@bu.edu
    Description: Profile page template for Mini FB. Displays user information including 
    profile image, name, city, and friends.
-->
{% extends 'mini_fb/base.html' %}

{% block content %}
<main style="max-width: 800px; margin: 0 auto; padding: 20px; font-family: Arial, sans-serif;">
    <div class="profile-card" style="background-color: #f0f2f5; border-radius: 8px; padding: 20px; margin-bottom: 20px; text-align: center; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        {% if profile.profile_image_url %}
        <img src="{{ profile.profile_image_url }}" alt="Profile Image" class="profile-image" style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover; border: 3px solid #fff; margin-bottom: 15px;">
        {% endif %}
        <h1 class="profile-name" style="margin: 0 0 10px 0; color: #1877f2; font-size: 24px;">{{ profile.first_name }} {{ profile.last_name }}</h1>
        <p class="profile-city" style="margin: 5px 0; color: #65676b; font-size: 16px;">{{ profile.city }}</p>
        <p class="profile-email" style="margin: 5px 0; color: #65676b; font-size: 16px;">{{ profile.email }}</p>
        {% if request.user.is_authenticated and request.user == profile.user %}
        <a href="{% url 'update_profile'%}" class="update-btn" style="display: inline-block; background-color: #1877f2; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px; margin-top: 10px; font-weight: bold;">Update Profile</a>
        {% else %}
        {% endif %}
    </div>
    {% if request.user.is_authenticated and request.user == profile.user %}

    <a href="{% url 'friend_suggestions' %}" class="find-friends-btn">Find Friends</a>

    {% else %}
    {% endif %}
    <!-- Friends Section -->
    <section style="background-color: #f0f2f5; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        <h2 style="color: #1877f2; margin-top: 0; border-bottom: 1px solid #dddfe2; padding-bottom: 10px;">Friends</h2>
        {% if profile.get_friends %}
        <ul style="list-style: none; padding: 0; margin: 0;">
            {% for friend in profile.get_friends %}
            <li class="friend-row" style="margin-bottom: 10px; padding: 10px; background-color: white; border-radius: 4px;">
                <a href="{% url 'show_profile' friend.pk %}" class="friend-link" style="display: flex; align-items: center; text-decoration: none; color: #050505;">
                    {% if friend.profile_image_url %}
                    <img src="{{ friend.profile_image_url }}" alt="{{ friend.first_name }}" class="friend-image" style="width: 50px; height: 50px; border-radius: 50%; margin-right: 15px; object-fit: cover;">
                    {% else %}
                    <div class="friend-placeholder" style="width: 50px; height: 50px; border-radius: 50%; background-color: #dddfe2; display: flex; align-items: center; justify-content: center; margin-right: 15px; font-size: 24px;">👤</div>
                    {% endif %}
                    <span class="friend-name" style="font-weight: bold;">{{ friend.first_name }} {{ friend.last_name }}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p class="no-friends" style="color: #65676b; font-style: italic; text-align: center; margin: 20px 0;">This user has no friends yet.</p>
        {% endif %}
    </section>

    <!-- Status Messages Section -->
    {% if request.user.is_authenticated and request.user == profile.user %}

    <a href="{% url 'create_status' %}" class="create-status-btn" style="display: block; background-color: #42b72a; color: white; padding: 10px 15px; text-decoration: none; border-radius: 4px; margin-bottom: 20px; text-align: center; font-weight: bold;">Create a comment</a>

    {% else %}
    {% endif %}
    
    <section class="status-section" style="background-color: #f0f2f5; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        <h2 class="status-header" style="color: #1877f2; margin-top: 0; border-bottom: 1px solid #dddfe2; padding-bottom: 10px;">Status Messages</h2>
        <div class="">
            {% for status_message in profile.statusmessage_set.all %}
            <div class="status-message" style="background-color: white; border-radius: 8px; padding: 15px; margin-bottom: 15px; box-shadow: 0 1px 2px rgba(0,0,0,0.1);">
                <span class="status-timestamp" style="color: #65676b; font-size: 12px; display: block; margin-bottom: 5px;">{{ status_message.timestamp }}</span>
                <p class="status-text" style="margin: 0 0 15px 0; line-height: 1.5;">{{ status_message.message }}</p>
                <div style="display: flex; gap: 10px; margin-bottom: 10px;">
                    {% if request.user.is_authenticated and request.user == profile.user %}

                    <a href="{% url 'delete' status_message.pk %}" class="delete-btn" style="color: #e41e3f; text-decoration: none; font-size: 14px; font-weight: bold;">Delete</a>
                    <a href="{% url 'update_status' status_message.pk %}" class="update-btn" style="color: #1877f2; text-decoration: none; font-size: 14px; font-weight: bold;">Update</a>

                    {% else %}
                    {% endif %}
                </div>
                {% for img in status_message.get_images %}
                    <img src="{{ img.image_file.url }}" alt="{{ img.caption }}" class="status-image" style="max-width: 100%; border-radius: 8px; margin-top: 10px;">
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </section>

    <a href="{% url 'news_feed' %}" 
    style="display: inline-block; margin-top: 15px; background: #007bff; color: white; padding: 8px 12px; border-radius: 5px; text-decoration: none; font-size: 14px;">
    View News Feed
    </a>

</main>
{% endblock %}